### ISSUE TITLE
Avoid repeating "name fragments" in module names

### ISSUE THREAD

**Issue by 4ZM** [christopheradams/elixir_style_guide#102]
Using the same "name fragment" (is there an established name for these?) multiple times in a module name causes some confusion. In particular in combination with alias. Advice against this.

``` elixir
defmodule Todo.Todo do
  alias Todo.Todo
  # Is confusing if you e.g. try to do alias Todo.SomeOtherModule here
end
```

For more background see: https://elixirforum.com/t/using-aliases-for-fubar-fubar-named-module/1723

**Comment by christopheradams** [comment]
On 09/20/2016 04:52 PM, Anders wrote:
> Using the same "name fragment" (is there an established name for these?)

The docs for `Module` just call each 'fragment' an **alias** which, if
you combine them, creates a new alias. :)

**Comment by christopheradams** [comment]
So maybe "Avoid repeating the same alias more than once in a module name."

**Comment by christopheradams** [comment]
Or more precisely, "Avoid using the same alias consecutively in a module name."

`Todo.Models.Todo` might be ok, for example.
