### ISSUE TITLE
About comparison testing 

### ISSUE THREAD

**Issue by marocchino** [christopheradams/elixir_style_guide#112]
I read the Elixir code and found that the following two styles are used at the same time:
```elixir
assert expected == actual
assert actual == expected
```
I'd like to unify for consistency, but what do you think?

**Comment by christopheradams** [comment]
Can you link to any examples of both styles?

Even though the `assert` macro doesn't care, obviously, there are a few reasons I would tend to favor `assert expected == actual`:

* tradition (other testing libraries that take args and use that order)
* if you use a pattern match instead of a truthy value, the expected pattern is on the left
* assertion errors are often written/understood in the form "expected A but got B"

**Comment by marocchino** [comment]
sure. 
- [actual == expected](https://github.com/elixir-lang/elixir/blob/master/lib/elixir/test/elixir/kernel/comprehension_test.exs#L35)
- [expected == actual](https://github.com/elixir-lang/elixir/blob/master/lib/elixir/test/elixir/base_test.exs#L12)

**Comment by christopheradams** [comment]
From the looks of it, every test module is internally consistent (they pick one order and stick with it), but there are examples of both styles.

I'd guess the motivation behind putting `actual` first is to highlight "this what what is being tested". For example [StringTest](https://github.com/elixir-lang/elixir/blob/master/lib/elixir/test/elixir/string_test.exs).

Would love to hear some more opinions.

**Comment by ericmj** [comment]
The great thing about the assert macro is that it doesn't enforce the actual, expected positions and that was actually one of the design decisions behind it because sometimes it's hard to determine which expression is "expected" and which is "actual".

It feels backwards to try to enforce a rule in a style guide that goes against the design decision of the tool.

**Comment by christopheradams** [comment]
> The great thing about the assert macro is that it doesn't enforce the actual, expected positions

Sure, but the style guide is about enforcing things the compiler or runtime don't care about. :)

I tend to think that `expected` first has better meaning but `actual` first has better style (especially when successive lines test the same function over and over). Therefore, it seems to be a wash. That would recommend against adding a rule for this.

**Comment by eksperimental** [comment]
[lexmag's elixir style guide](https://github.com/lexmag/elixir-style-guide) is about to include this rule
https://github.com/lexmag/elixir-style-guide/issues/11

**Comment by christopheradams** [comment]
Thanks for the pointer @eksperimental

For context the linked issue recommends that the "expected result goes on the right", in other words: `actual == expected`

Since this guide doesn't try to be unnecessarily "opinionated", I'm not sure if there's a way forward here.

**Comment by DavidAntaramian** [comment]
@christopheradams I don't think the style guide needs to be opinionated about it, just point out "be consistent."

As pointed out in the linked issue, one of the problems with the phrasing is that it will always be `expected = actual` when performing a pattern match as a test acceptance.

**Comment by christopheradams** [comment]
This may be too blindingly obvious, but something like:

## Testing

* When writing ExUnit assertions, be consistent about the order of the expected and actual values under testing. If in doubt, place the expected result on the right, unless the assertion is a pattern match.

  ```elixiir
  # preferred
  assert actual_function(1) == true
  assert actual_function(2) == false

  # not preferred
  assert actual_function(1) == true
  assert false == actual_function(2)

  # required, if the assertion is a pattern match
  assert {:ok, expected} = actual_function(1)
  ```

**Comment by christopheradams** [comment]
Added a new [testing section](https://github.com/christopheradams/elixir_style_guide#testing) with this `actual == expected` guideline. Thanks everyone!
