### ISSUE TITLE
Add translations section

### ISSUE THREAD

**Issue by christopheradams** [christopheradams/elixir_style_guide#125]
* Korean: @marocchino [[link][marocchino]] 
* Japanese: @upscent [[link][upscent]] and @kenichirow [[link][kenichirow]]

[upscent]: https://github.com/upscent/elixir_style_guide/tree/development
[kenichirow]: https://github.com/kenichirow/elixir_style_guide/blob/feature/japanese/README.ja.md
[marocchino]: https://github.com/marocchino/elixir_style_guide/blob/new-korean/README-koKR.md

**Comment by christopheradams** [comment]
@upscent and @kenichirow is there a way for you two to collaborate on the japanese translations? how close are they?

**Comment by upscent** [comment]
Sorry for my late reply.

@kenichirow's translation is nearly completed and very easy to understand, so I think it's good to adopt his translation 😄

**Comment by kenichirow** [comment]
@upscent Thank you! 
Please send PR if my translations are something wrong

**Comment by christopheradams** [comment]
Do you have any tips on how to manage a translation? I can see how it's done on [Ruby Style Guide], but I don't see the instructions written down anywhere. For new translation the steps look like:

1. fork the main repository
2. on your master, copy `README.md` to `README-${lang}.md`, and commit your translations there
3. add the main repository as an upstream remote, and pull changes from it

What do you think?

[Ruby Style Guide]: https://github.com/bbatsov/ruby-style-guide

**Comment by kenichirow** [comment]
I think that's OK
ruby-style-guide's translation process is correct to me.

**Comment by kenichirow** [comment]
- [x] separate README.${lang}.md from README.md
- [x] merge adn rebase upstream 
- [] catch up the originals

https://github.com/kenichirow/elixir_style_guide/commits/master

**Comment by christopheradams** [comment]
@kenichirow and @marocchino What about also translating the repo description text of your forks? Right now they all say the original "A community driven style guide for Elixir". That description text is often displayed when sharing the link. It would make sense to localize it.
