### ISSUE TITLE
@callback in module attributes

### ISSUE THREAD

**Issue by rhruiz** [christopheradams/elixir_style_guide#139]
Where should we put `@callback`s in [module attribute ordering](https://github.com/christopheradams/elixir_style_guide/blob/master/README.md#module-attribute-ordering)?

**Comment by christopheradams** [comment]
I think any `@callback` should be last after all module attributes but before any functions. It would be great to add this to the ordering.

I can think of a few more guidelines:

* callbacks should have a `@doc` like regular functions
* the types should follow formatting rules for typespecs
* if a callback is optional, the `@optional_callbacks` attribute should be listed right after it

What do you think?

**Comment by rhruiz** [comment]
Created a PR, what do you think?
