### ISSUE TITLE
function, pipe and the ()

### ISSUE THREAD

**Issue by GildedHonour** [christopheradams/elixir_style_guide#144]
Guess what somethingN is: variable or function?

`my_string |> something1 |> something2 |> something3`

I think with the pipe a function should be called like this:

`my_string |> something1() |> something2() |> something3()`

**Comment by christopheradams** [comment]
> Guess what somethingN is: variable or function?
>
> `my_string |> something1 |> something2 |> something3`

It has to be a function. You can't pipe to a variable.

> I think with the pipe a function should be called like this:
>
> `my_string |> something1() |> something2() |> something3()`

Using parentheses for a one-arity function in a pipe is entirely valid. If this style starts to catch on, we should consider changing this guide.

**Comment by GildedHonour** [comment]
I know that I can't use a variable in a pipe, but that doesn't prevent me from making a bug which I'll catch only at runtime.

**Comment by GildedHonour** [comment]
>If this style starts to catch on, we should consider changing this guide.

The  purpose of this guide to make a  list of styles to catch on.

**Comment by christopheradams** [comment]
> I know that I can't use a variable in a pipe, but that doesn't prevent me from making a bug which I'll catch only at runtime.

On the contrary, using a variable in a pipe will give you an `undefined function` compilation error.

> The purpose of this guide to make a list of styles to catch on.

Good point! A PR would probably be the next step then.

**Comment by arialblack14** [comment]
@christopheradams Would you like me to submit a PR?

**Comment by christopheradams** [comment]
@arialblack14 Yes a PR would be welcome, or even the proposed rule as a comment on this thread!

**Comment by christopheradams** [comment]
I did a search over Elixir core libraries and popular packages to get a sense of the prevalence of the two pipe styles (`"^\s+\|>.*[a-z]$"` vs `"^\s+\|>.*\(\)$"`).

The style without parentheses outnumbers the parentheses style almost 2-1. However, if I narrow down the search to elixir, plug, phoenix, and ecto, the split is about 50-50. Newer code tends to use parentheses (as this has been the recommended style in @lexmag's [style guide](https://github.com/lexmag/elixir-style-guide#zero-arity-parens) for some time).

I've merged @arialblack14's PR with this rule change. Thanks all!
