### ISSUE TITLE
Spanish translation

### ISSUE THREAD

**Issue by albertoalmagro** [christopheradams/elixir_style_guide#147]
This is just to record that I am creating the Spanish translation for this guide.

https://github.com/albertoalmagro/elixir_style_guide/blob/spanish/README_esES.md

**Comment by christopheradams** [comment]
Awesome! Thanks. We'll have to add this to the translations list.

**Comment by albertoalmagro** [comment]
Added PR https://github.com/christopheradams/elixir_style_guide/pull/148

**Comment by christopheradams** [comment]
Very good!
