### ISSUE TITLE
Elixir Style Guide in pt_BR underway

### ISSUE THREAD

**Issue by gusaiani** [christopheradams/elixir_style_guide#150]
Hey @christopheradams and all,

thanks for Elixir Style Guide.

Today I started work on a pt_BR version of the guide at https://github.com/gusaiani/elixir_style_guide/blob/master/README_ptBR.md

Help is welcome / Ajuda é bem-vinda!

Thank you

**Comment by christopheradams** [comment]
It's a great start!

**Comment by christopheradams** [comment]
Closed by #153.
