### ISSUE TITLE
Switch to hard tabs from recommended 2-spaces

### ISSUE THREAD

**Issue by jononomo** [christopheradams/elixir_style_guide#152]
Indentation should use hard tabs rather than spaces.

Because editors can be configured to display a single hard tab as any number of spaces, it is easier to quickly toggle settings to get a clearer grasp of the code indentation and flow.

On the other hand, there is no advantage to preferring spaces over tabs.

**Comment by ericmj** [comment]
I haven't seen a single piece of Elixir code using tabs instead of spaces.

**Comment by jononomo** [comment]
It is still relatively early - in my opinion it would be better to adopt this convention sooner rather than later.  Indentation is the best use-case for the tab key, and indentation with spaces has no benefit.

There are two reasons why the tab key is especially good for indentation:

1. It makes it easy to adjust the adjust the amount of displayed indentation space without altering the file -- because editors allow you to configure how wide a tab should be displayed. 

2. Using tabs makes it much easier to grasp indentation when a section of code is selected -- see my screenshot for an example.

Also, tab-indentation is in use in the Erlang community.

![screen shot 2017-06-26 pm](https://user-images.githubusercontent.com/5942683/27567523-55d1b818-5aba-11e7-884f-40a3fb5354c6.png)

**Comment by alexarnon** [comment]
This has been hashed and rehashed ad nauseam by the Python community.
At this point this kind of discussion is a waste of time - please use
spaces.

**Comment by optikfluffel** [comment]
I will just leave this here: [Developers Who Use Spaces Make More Money Than Those Who Use Tabs](https://stackoverflow.blog/2017/06/15/developers-use-spaces-make-money-use-tabs/)

![trollsir](https://user-images.githubusercontent.com/379915/27584393-22ce80b2-5b38-11e7-8e99-92befd861a02.jpg)

**Comment by christopheradams** [comment]
There is a broad consensus within the Elixir community and core team for 2-space indentation, as well as using spaces to indent for alignment. We try to follow their style.

It was thoughtful of you to present considered reasons for your differing viewpoint.

**Comment by jpscaletti** [comment]
> This has been hashed and rehashed ad nauseam by the Python community.
> At this point this kind of discussion is a waste of time - please use spaces.

In the Python community, the spaces won because it was already too late to change, not because it was objectively the *best* option.

I like this metaphor: Using spaces it's like having a fixed width page (*“best viewed in Internet Explorer x.y!”*) while tabs are the "responsive" alternative

**Comment by jpscaletti** [comment]
Nevermind. Phoenix generators use spaces, so it's already too late :(
