### ISSUE TITLE
Pipe styling and debugging troubles

### ISSUE THREAD

**Issue by zcotter** [christopheradams/elixir_style_guide#156]
Hi there!

The [section on using the pipe operator](https://github.com/christopheradams/elixir_style_guide#pipe-operator) suggests that for multiline pipes, the pipe operator should go on the next line after an expression:
```elixir
some_string
|> String.downcase()
|> String.strip()
```
The guide acknowledges this causes a problem with debugging:
> While this is the preferred method, take into account that copy-pasting multiline pipelines into IEx might result in a syntax error, as IEx will evaluate the first line without realizing that the next line has a pipeline.

This style makes debugging quite tedious, as developers must copy-paste each individual line into the console. In this case, I think it is worth trading-off style for ease-of-use.

Another format the community might consider is:
```elixir
# Multiline pipelines should be indented, with the pipe 
#   operator trailing the previous expression
some_string |>
  String.downcase() |>
  String.strip()
```
The indentation of the following expressions indicates that they are each a continuation of the multiline pipeline statement on the first line. I'd also be open to any other format that makes debugging easier and also is readable.

Would the community be open to a pull request that changes this style guideline to better facilitate debugging?

**Comment by christopheradams** [comment]
@zcotter You make an excellent case. Nevertheless, the current style for the pipe operator is overwhelmingly preferred by the standard libraries and top packages, and we won't consider deviating from it at this time.

I believe there are ways around the problem posed by IEx, such as wrapping the expression in parentheses.
