### ISSUE TITLE
More guidance for indenting, aligning in case statements.

### ISSUE THREAD

**Issue by raarts** [christopheradams/elixir_style_guide#157]
(I'm taking case statements as an example, but it can be applied elsewhere. Feel free to adjust the title of this issue.)

I feel the style guide can be more explicit about the following:

```
    case env.method do
      :get -> %{env | status: 400, body: Poison.encode!(%{id: "Sdds"})}
      _ -> %{env | status: 405, body: Poison.encode!(%{status: "error"})}
    end
```

Now, I find this ugly, so I ended up with this, which I find much easier to read. 

```
    case env.method do
      :get -> %{env | status: 400, body: Poison.encode!(%{id: "Sdds"})}
      _    -> %{env | status: 405, body: Poison.encode!(%{status: "error"})}
    end
```

And yes, you might need to change adjacent lines when you change the first clause.

It gets more problematic when one of the case clauses is textually long:

 ```
    case env.method do
      :exceptionally_long_atom -> %{env | status: 400, body: Poison.encode!(%{id: "Sdds"})}
      _ -> %{env | status: 405, body: Poison.encode!(%{status: "error"})}
    end
```

or, when aligning:

 ```
    case env.method do
      :exceptionally_long_atom -> %{env | status: 400, body: Poison.encode!(%{id: "Sdds"})}
      _                        -> %{env | status: 405, body: Poison.encode!(%{status: "error"})}
    end
```

The style guide seems to favour (from the examples):
 ```
    case env.method do
      :exceptionally_long_atom ->
        %{env | status: 400, body: Poison.encode!(%{id: "Sdds"})}
      _ 
        -> %{env | status: 405, body: Poison.encode!(%{status: "error"})}
    end
```

Which, to me, is really ugly and not easy to read. 

Not really knowing where I'm going with this, just something I bumped into when trying to make my code match the style guide.

**Comment by christopheradams** [comment]
Lots to consider. As an aside, I'm guessing you meant to format the last example like this:

```elixir
   case env.method do
     :exceptionally_long_atom ->
       %{env | status: 400, body: Poison.encode!(%{id: "Sdds"})}
     _ ->
       %{env | status: 405, body: Poison.encode!(%{status: "error"})}
   end
```

**Comment by raarts** [comment]
Yes, you're right. Sorry about that. Still think that's ugly though, especially with more clauses.

**Comment by christopheradams** [comment]
The preferred styles for case statements based on the Elixir code formatter are:

```elixir
case env.method do
  :get -> %{env | status: 400, body: Poison.encode!(%{id: "Sdds"})}
  _ -> %{env | status: 405, body: Poison.encode!(%{status: "error"})}
end
```
and:

```elixir
case env.method do
  :get ->
    %{env | status: 400, body: Poison.encode!(%{id: "Sdds"})}

  _ ->
    %{env | status: 405, body: Poison.encode!(%{status: "error"})}
end
```

Hopefully the latter one addresses your readability concerns.
