### ISSUE TITLE
camelCase vs PascalCase

### ISSUE THREAD

**Issue by bjunc** [christopheradams/elixir_style_guide#161]
The term `CamelCase` is being used in places where `PascalCase` might be more appropriate.  I think of them like this:

`camelCase`
`PascalCase`
`snake_case`
`kebab-case`
`Initialcapped`

**Comment by christopheradams** [comment]
This has been discussed before, most recently in #92.

We've decided to stick with `CamelCase` as this is the term used in the official Elixir docs.

**Comment by bjunc** [comment]
Ah, I see.  I even searched "CamelCase" to see if there was a previous issue.  Sorry about that.

I think the gripe I have with camel case is that these are _both_ camel case:
`camelCase` and `CamelCase`.  Whereas pascal case is only written as `PascalCase`.  I see where you're coming from regarding convention established in the Elixir docs though.

**Comment by christopheradams** [comment]
Yes, thanks for the suggestion anyway! Hopefully the casing rules are clear enough from the context even if the term is ambiguous.
