### ISSUE TITLE
Missing a section about maps

### ISSUE THREAD

**Issue by lobo-tuerto** [christopheradams/elixir_style_guide#169]
There is nothing in the guide about stuff like this:

```elixir
%{ a: 1, b: 2 }

%{ :a => 1, 2 => :b }
```

**Comment by christopheradams** [comment]
Something like this?

* Use the `key: value` shorthand syntax for all keys in maps that are atoms.

  ```elixir
  # not preferred
  %{:a => 1, :b => 2, "c" => 0}

  # preferred
  %{"c" => 0, a: 1, b: 2}
  ```

**Comment by lobo-tuerto** [comment]
Yeah, that's a good start! :)

We could argue about being consistent first, and maybe only use that shorthand syntax only when all keys are atoms probably?

**Comment by christopheradams** [comment]
> We could argue about being consistent first, and maybe only use that shorthand syntax only when all keys are atoms probably?

Yes, I would agree with this.

**Comment by christopheradams** [comment]
@lobo-tuerto What do you think of this?

* Use the shorthand key-value syntax when all the keys in a map are atoms.

  ```elixir
  # not preferred
  %{:a => 1, :b => 2, :c => 0}

  # preferred
  %{a: 1, b: 2, c: 3}
  ```

* Use the verbose key-value syntax when not all the keys in a map are atoms.

  ```elixir
  # not preferred
  %{"c" => 0, a: 1, b: 2}

  # preferred
  %{:a => 1, :b => 2, "c" => 0}
  ```

**Comment by lobo-tuerto** [comment]
@christopheradams That looks good!
