### ISSUE TITLE
Suggestion on Module Attribute Ordering 

### ISSUE THREAD

**Issue by mustafaturan** [christopheradams/elixir_style_guide#173]
The `@behaviour` should come at least after `alias`(after `require` is good). 

**Reason to change request:** 

The current order of `@behaviours` can't get benefit of `alias`.

**Example:**

The following approach doesn't recognize the aliased module:
```elixir
defmodule Sample.Resource.AccessToken do
  @moduledoc false

  # doesn't recognize aliased module which needs to be written as 'Sample.Resource'
  @behaviour Resource 

  alias Sample.Resource
  ...
end
```

but if we follow the following order, it will not give any warning:

```elixir
defmodule Sample.Resource.AccessToken do
  @moduledoc false

  alias Sample.Resource
  require SomeOther

  @behaviour Resource
  ...
end
```

Ref: https://github.com/christopheradams/elixir_style_guide#module-attribute-ordering

**Comment by christopheradams** [comment]
@mustafaturan Thanks for the suggestion. We've discussed this previously in #141 and decided not to change the recommended module attribute ordering.
