### ISSUE TITLE
Thoughts on public/private function ordering

### ISSUE THREAD

**Issue by AndroidOatmeal** [christopheradams/elixir_style_guide#181]
Hello!

I was reading through the style guide (thanks so much for maintaining this great project) and noticed there wasn't any suggestions on public/private function ordering in modules.

I've been working full-time on Elixir projects for about two years now and I've noticed a division on this topic. In many other programming languages there is a convention to put public functions at the top of a file. This makes it easy to skim the public API for a module/class, and then you can dive into the details and scroll further down to view private function implementations if desired.

However, when I dive into projects like ecto or phoenix, I see a pattern of bundling public functions close together with their associated private functions. Using DDD-style "context" modules has been a common pattern in developing Phoenix applications, and these modules often have a large public API with many private functions. From what I've seen, keeping these private functions close to the public functions in which they are used is fairly common.

To summarize, there are two ways I've seen modules organized in elixir:
1. All public functions listed at the top, private functions at the bottom. This is easier to skim the public API but may require jumping around the file in order to get the full picture of what is happening.
```
defmodule FooBar.SomeModule do
  # Public functions at the top
  def public_function_one(foo, bar) do
    ...
  end
  
  def public_function_two(foo, bar) do
    ...
  end
  
  def public_function_three(foo, bar) do
    ...
  end

  # Private functions at the bottom
  defp private_function_one(foo, bar) do
    ...
  end

  defp private_function_two_a(foo, bar) do
    ...
  end

  defp private_function_two_b(foo, bar) do
    ...
  end
  
  defp private_function_three(foo, bar) do
    ...
  end
end
```

2. Public functions are followed by associated private functions. This makes it difficult to skim the public API for a module, but generally all the contextual information you need will be in one place within the file.

```
defmodule FooBar.SomeModule do
  # Public functions at the top, followed by their associated private functions
  def public_function_one(foo, bar) do
    ...
  end

  defp private_function_one_a(foo, bar) do
    ...
  end

  def public_function_two(foo, bar) do
    ...
  end

  defp private_function_two_a(foo, bar) do
    ...
  end

  defp private_function_two_b(foo, bar) do
    ...
  end

  def public_function_three(foo, bar) do
    ...
  end

  defp private_function_three(foo, bar) do
    ...
  end
end
```

Should the Elixir style guide have any opinions on this? What about large modules vs small ones? Or is this outside of the scope of what a style guide should be doing?

I personally find option # 2 difficult to read and it can be a little overwhelming to browse certain larger modules. Open to any and all thoughts on the subject. Thanks!

**Comment by christopheradams** [comment]
I prefer option # 2, keeping private functions proximate to the ones that use them (as you can observe in Ecto and the standard library), rather than strictly separating the module into public and private.

In a well-written module, the public functions will be easy to pick out from their `@doc` tags, while their private functions can be tucked below and kept accessible.

Any helper functions that are used by multiple functions can still be placed together at the end of the module rather than after whichever function first used them.

This module illustrates this nicely: https://github.com/elixir-lang/elixir/blob/030e0c7b53023ab2d75780dbdfe54c9cce225385/lib/elixir/lib/io/ansi/docs.ex

**Comment by AndroidOatmeal** [comment]
@christopheradams Thanks for the reply, you make some good points. I think you're probably right in this case. Using `@doc` certainly draws attention to the public functions in a module, but I'll note that there is sometimes a difference here between `@doc` usage in internal vs external projects. On many of my Phoenix projects we don't use `@doc`s for our context functions because they're only used internally and generally intuitively named. With libraries like Ecto and the elixir standard library, having `@doc`s makes more sense since you have a wide audience of people using the libraries.

The module you linked to does give me some ideas though. Prefixing each public function with `@spec` would also make any module skimmable.

Is the ordering of public/private functions something we want to include in the styleguide? If so, I'm happy to take a crack at it.

**Comment by jillionlabs** [comment]
I prefer keeping private functions out of the way at the bottom of the file; however, I’d be OK with option #2 if private functions all started with an underscore. This makes them both easier to identify and also prevents them from being mass-imported into other modules if someone forgets the p in defp.

**Comment by christopheradams** [comment]
There's no precedent at all for prefixing private functions with an underscore.

I don't think the guide can take a position on private function placement, such as saying that they should always be at the bottom of the module, or below the function that uses them.
