### ISSUE TITLE
Deeply nested one-arity function calls?

### ISSUE THREAD

**Issue by daniellizik** [christopheradams/elixir_style_guide#186]
Some of my absinthe input types look messy:

```
input_foo :foo do
  field :bar non_null(list_of(non_null(:fizzbuzz)))
end
```

This is hard to read. Do you recommend pipes or forgoing the parenthesis at all?

```
non_null list_of non_null :fizzbuzz
# or
:fizzbuzz |> non_null |> list_of |> non_null
```

I think using pipes like this is sort of confusing because you sort of need to read it backwards. Is there some idiomatic and clean way of writing nested function calls like this? I'm a beginner to elixir.

**Comment by christopheradams** [comment]
The maintainers of Absinthe write it the first way, e.g.:

```elixir
      field :foo_wrapped_int_list, :foo do
        arg :input, non_null(list_of(non_null(:integer)))
      end
```

https://github.com/absinthe-graphql/absinthe/blob/4c16232a40d06dcb7979464159b36a9f03a1ff2e/test/absinthe/phase/document/arguments/coerce_lists_test.exs#L17-L19

I personally don't see much of a readability problem here.

**Comment by daniellizik** [comment]
ok, thanks.
