### ISSUE TITLE
List projects which follows the style

### ISSUE THREAD

**Issue by Irio** [christopheradams/elixir_style_guide#2]
Like [Ecto](https://github.com/elixir-lang/ecto).

**Comment by eksperimental** [comment]
I think we could close this on.
I think maintaining a list will be a daunting task. maybe a list of the most popular projects and on a separate page?

**Comment by christopheradams** [comment]
I've created a wiki page for the purpose of tracking which packages may be referenced for style guidelines: https://github.com/christopheradams/elixir_style_guide/wiki/Package-List
