### ISSUE TITLE
Naming: Modules

### ISSUE THREAD

**Issue by sepowitz** [christopheradams/elixir_style_guide#200]
Hey there,

First off, I just wanted to say how helpful I've found this documentation – it's very thorough and makes for some really readable Elixir code. 

One (very small) inconsistency I noticed, was in the [Naming: Modules](https://github.com/christopheradams/elixir_style_guide#camel-case) section.

####  Currently it states:

Use `CamelCase` for modules (keep acronyms like HTTP, RFC, XML uppercase). 

I believe it should be:

Use `PascalCase` for modules (keep acronyms like HTTP, RFC, XML uppercase). 

The difference being that:

`camelCase` uses a lowercased first letter
`PascalCase` uses an uppercase first letter

Thanks again!
Sebastian

**Comment by christopheradams** [comment]
Hi @sepowitz thanks for the i out. We've discussed this issue before most recently in #161 and have chosen to follow the Elixir [Naming Conventions](https://hexdocs.pm/elixir/master/naming-conventions.html) documentation which uses "CamelCase".
