### ISSUE TITLE
Is __MODULE__ preferable?

### ISSUE THREAD

**Issue by styx** [christopheradams/elixir_style_guide#22]
``` Elixir
defmodule SomeNamespace.SomeModuleName do
  defstruct name: nil
  @type t :: %__MODULE__{name: String.t}

  def new, do: %__MODULE__{}
end
```

What do you think about using `__MODULE__` as it is used in `new` method.
(Already saw `@type t :: %__MODULE__` in Elixir sources and that looks good.) And in general what about a recommendation to use `__MODULE__` through whole module against to manual qualification of the name like `SomeNamespace.SomeModuleName`. Hope I was clean enough (:

**Comment by schnittchen** [comment]
Can somebody elaborate please? Will using __MODULE__ "just" make my code more stable against renaming? (if so, wouldn't @chrismccord 's aliasing defeat the purpose?)

**Comment by chrismccord** [comment]
> Can somebody elaborate please? Will using MODULE "just" make my code more stable against renaming? (if so, wouldn't @chrismccord 's aliasing defeat the purpose?)

yes. For me, doing a find/replace in a file should my module name change is a worthy tradeoff. Note: I'm fine with `__MODULE__` when I just want to grab a reference to it, but I prefer an alias for structs, since you're often passing those around and accepting them as arguments. To me, the alias reads clearer. I'd rather see:

```elixir
def name(%User{fname: fname, lname: lname}), do: fname <> " " <> lname
```

than

```elixir
def name(%__MODULE__{fname: fname, lname: lname}), do: fname <> " " <> lname
```

**Comment by schnittchen** [comment]
Thx @chrismccord, that makes total sense.

**Comment by obrok** [comment]
I sometimes do

```elixir
    alias __MODULE__, as: SomeModule 
```

to guard against renames as well as have a nice looking `SomeModule` instead of `__MODULE__` in the code.

**Comment by phanimahesh** [comment]
I like @obrok's suggestion.

**Comment by whatyouhide** [comment]
I'm :+1: on @chrismccord suggestion, it's the one I use regularly in my code.

**Comment by Calamari** [comment]
Intetresting reasoning. It totally makes sense. If this rule gets to the Styleguide, can this "why?" be included? I think reading the styleguide is good, but also know why those particular rules are useful, can really help adopting (and remembering) them.

**Comment by christopheradams** [comment]
Please check PR #114 and let me know if you think it addresses this issue. It advises using `__MODULE__` for module self-references, and recommends using an alias if you desire a clearer, unique name.
