### ISSUE TITLE
A few things are missing

### ISSUE THREAD

**Issue by sam113101** [christopheradams/elixir_style_guide#48]
First, you say to put spaces around operators. There was no mention of ranges, they use '..' which can be seen as an operator, yet I don't think most people put spaces around those.

Then there's '::'. They're present in specs (to specify the return type) and binaries. Should we surround them with spaces in both cases?

Maps and structs. If I understand correctly, tuples must be written {:as, :such}, however, does it still stand for maps and structs? %Point{x: 0, y: 0} seems a bit "crowded" to me, but I've seen it in multiple repos.

List patterns, head and tail. I've seen both [head|tail] and [head | tail], and I'm not sure which one to use. The second one looks cleaner to me, and it fits with the rule that says to put spaces around operators. You've used [first|rest] in your examples.

I probably forgot a few other things, but this is all I can think of right now.

**Comment by eksperimental** [comment]
In the Elixir code base we have completely vanished the us of the `[head|tail|` and `1 .. 2` style in favour of `[head | tail]` and `1..2` . So I think it's a good addition to the style guide.
@lexmag's elixir-style-guide covers a lot of this in the [source-code layout section](https://github.com/lexmag/elixir-style-guide#source-code-layout).

**Comment by christopheradams** [comment]
Addressed in 977e6b6 and 7418d2a

`::` should have spaces (not single-argument), and never spaces inside braces.

Thanks!
