### ISSUE TITLE
Multi-line arg list in function calls

### ISSUE THREAD

**Issue by jesenko** [christopheradams/elixir_style_guide#58]
There is currently no guideline on function calls with multi-line arg lists. For use-cases I encountered most often, following rules works for me:

``` elixir
# call with parentheses, first argument in-line with function
some_func(:first_arg,
          :second_arg,
          :third_arg)

# call with parentheses, first argument in new line
some_funct(
  :somewhat_long_expression_for_argument,
  :second_arg,
  :third_arg)

# call without parentheses and keyword list
some_funct :regular_arg,
  keyword_arg: "option",
  other_keyword_arg: "there"
```

I am aware that third example (without parentheses) is conflicting with _Use parentheses in function calls_, however I find it quite verbose in various _configuration_-related code with long keyword lists.

Thoughts? Suggestions?

**Comment by eksperimental** [comment]
In elixir code base i think no. 1 is discourage, since indentation is always two spaces for each level.

**Comment by eksperimental** [comment]
I would propose:

```elixir
# call with parentheses, first argument in-line with function
some_func(:first_arg,
  :second_arg,
  :third_arg
)
```

this is quiet common to be found in tests, where a function is an argument, for example: 
https://github.com/elixir-lang/elixir/blob/98a0999c2e24a02089f91244543203d3764cf196/lib/mix/test/mix/tasks/compile.yecc_test.exs#L18-L22

```elixir
assert_raise Mix.Error, fn ->
  capture_io fn ->
    Mix.Tasks.Compile.Yecc.run ["--force"]
  end
end
```

**Comment by whatyouhide** [comment]
Visually number 1 is really nice but in my experience, it's annoying because of VCS. Changing the name of the function will force you to reindent all the arguments, resulting in a 3-lines diff instead of a 1-line one.

@eksperimental is close but I think the cleanest solution is:

```elixir
some_func(
  :first_arg,
  :second_arg,
  :third_arg
)
```

Wdyt?

**Comment by eksperimental** [comment]
:+1: for your proposal @whatyouhide

**Comment by jesenko** [comment]
+1 for @whatyouhide proposal, i.e. avoiding specifying first argument in-line with function call altogether. Putting closing `)` in new line indeed looks cleaner. Works ok also when piping result with `|>` e.g.

```elixir
# without newline
val = 
  some_method(
    arg1,
    arg2)
  |> something
  |> something_else
```
```elixir
# with newline, looks cleaner to me
val = 
  some_method(
    arg1,
    arg2
  )
  |> something
  |> something_else
```

@whatyouhide, @eksperimental What is your opinion on usage without parentheses?

**Comment by eksperimental** [comment]
I like your second example.

no parenthesis would mean you will have to put the first argument in the first line.
 
```elixir
val = 
  some_method arg1,
    arg2,
    arg3
  |> something
  |> something_else
```

personally when breaking into several lines, I think parenthesis it clear. when you see the closing parens it reminds you that a function is above

If you have two lines, that's ok, i think

```elixir
val = 
  some_method arg1, arg2, something_else,
    arg100, somemore, etc, etc, etc
  |> something
  |> something_else
```

I think here it applies the same rules as for ", do: ", vs. "do.. end". Two lines, no need for an end, more yes.

**Comment by jesenko** [comment]
@eksperimental Agreed, I would probably avoid usage without parenthesis when combined with `|>` or when nesting calls (e.g. `some_method(other_method(...multiline args...))`

I was actually wondering about your general opinion on calls without parenthesis (my example 3) - do you think that usage without parenthesis be avoided altogether?

**Comment by eksperimental** [comment]
@jesenko sorry for sucha a late reply (I must have missed your message). I would discourage the use without parenthesis in your example-3.
but this example works without parenthesis.

```elxiir
assert_raise Mix.Error, fn ->
  capture_io fn ->
    Mix.Tasks.Compile.Yecc.run ["--force"]
  end
end
```

So to wrap up, i would go with:

```elixir
some_func(
  :first_arg,
  :second_arg,
  :third_arg
)

val = 
  some_func(
    :first_arg,
    :second_arg,
    :third_arg
  )

# when followed by  a pipe-line: without newline
val = 
  some_method(
    arg1,
    arg2)
  |> something
  |> something_else 

# alternative suggestion, that parenthesis could be when last argument finishes with and `end` delimiter
assert_raise Mix.Error, fn ->
  capture_io fn ->
    Mix.Tasks.Compile.Yecc.run ["--force"]
  end
end
```

I would like to know your opinion, and get to an agreement for a PR

**Comment by jesenko** [comment]
@eksperimental  :+1: for the suggested approach. Usage without parentheses should probably be limited to macros, where it is already quite prevalent, e.g.:
```
config :logger, :console,
    level: :info,
    format: "$date $time [$level] $metadata$message\n",
    metadata: [:user_id]
```

**Comment by corroded** [comment]
@eksperimental Is this still good to go? I am unsure how to move forward with this. Let me know if you need help! 👍

**Comment by eksperimental** [comment]
It looks like there had been some sort of agreement,
so @corroded please submit a PR if you feel like, 
so we can discuss over real code. 
Thank you.

**Comment by christopheradams** [comment]
The formatter will handle multi-line function arguments, including placement of parentheses.

For more information we can consult: https://hexdocs.pm/elixir/Code.html#format_string!/2-parens-and-no-parens-in-function-calls
