### ISSUE TITLE
Blank line after multiline pipe

### ISSUE THREAD

**Issue by bbense** [christopheradams/elixir_style_guide#60]
After you use a multiline pipe to set a result leave a blank line to as a visual marker that the pipe 
is "over".

This : 

```
inner =
  args
  |> Enum.map(fn(tp) -> format_doc_arg(tp) end)
  |> Enum.join(", ")

"("<>inner<>")"
```

Not This: 

```
inner =
  args
  |> Enum.map(fn(tp) -> format_doc_arg(tp) end)
  |> Enum.join(", ")
"("<>inner<>")"
```

**Comment by doomspork** [comment]
:+1:

**Comment by kholbekj** [comment]
Does the pipe really have anything to do with why that looks better? Seems like a general multiline assignment issue to me.

```
something = 
  if 1==2 do
    2
  else
    4
  end
wat
````

**Comment by bbense** [comment]
There is a difference in that the pipe construct doesn't have an "end" tag, but I like applying "blank line after multiline assignment rule".

**Comment by doomspork** [comment]
:+1: for the extra line

**Comment by eksperimental** [comment]
:+1:

**Comment by kholbekj** [comment]
I agree on the end tag, but think both that and the lack of pipe operator are too subtle visual clues, so I'm all in for blank line rule! :+1:

**Comment by eksperimental** [comment]
@bbense, @kholbekj: I would like to see in words both options, and see which one makes more sense.
any ideas how it should read like?

**Comment by vishaldeepak** [comment]
👍

**Comment by corroded** [comment]
@bbense @kholbekj @eksperimental Just updating this and cleaning up stuff. Based on the discussions here, it looks like the consensus is to just add a blank line for multiline assignments:

- Add a blank line after a multiline assignment as a visual cue that the assignment is 'over'

```elixir
# not preferred
inner =
  args
  |> Enum.map(fn(tp) -> format_doc_arg(tp) end)
  |> Enum.join(", ")
"("<>inner<>")"

# also not preferred
something = 
  if 1==2 do
    2
  else
    4
  end
wat

# preferred
inner =
  args
  |> Enum.map(fn(tp) -> format_doc_arg(tp) end)
  |> Enum.join(", ")

"("<>inner<>")"

# preferred
something = 
  if 1==2 do
    2
  else
    4
  end

wat
```

As a side note, should I separate the two examples in their own preferred/not preferred section or just combine them like what I did above?

**Comment by eksperimental** [comment]
@corroded I would go with "not prefered" followed by "prefered"; and then again.
Please submit a PR, it will be much easier to work over that. I would use space around `==`, and change the `wat` variable to a more meaningful name.
maybe simplify a bit more the examples
