### ISSUE TITLE
Naming functions with verbs

### ISSUE THREAD

**Issue by maxim** [christopheradams/elixir_style_guide#67]
This is something I've been debating in my code. In OOP you have objects that combine state and behavior, so methods on those objects can be named like `user.full_name` or `struct.byte_size`, etc. In functional your data has no behavior, so it's always operated upon: `User.full_name(my_user)`, `Struct.byte_size(my_struct)`. However, this reads weird. In this configuration functions should say something like `User.get_full_name(my_user)`, or `Struct.calc_byte_size(my_struct)`. In various code examples I see that the verb tends to be omitted, which also makes sense, because if it wasn't, every function would be prepended with things like `get_`, and `calc_`, which creates noise. So should we consider the verb implicit and just omit it? Or maybe have a convention where we omit it only in cases where it would be something very generic like `get_` or `calc_`?

**Comment by benwilson512** [comment]
I do not think `get_` and so on are the right answer. Particularly when pure, functions are best thought of as mappings from inputs to outputs. So for example `full_name` maps the domain of users to the domain of full names. `byte_size` maps your domain of structs to the domain of byte sizes. It's irrelevant whether it does so by "calculating" or by simply retrieving a map, or making up a random number. What's relevant is the domain of output.

The exception to this are side effect oriented functions. Those often use verb oriented language like `Repo.insert` or `File.write`.

**Comment by maxim** [comment]
Hm, almost every Elixir function regardless of side effects is actually a verb, check out Enum for example: `dedup`, `concat`, `unzip`, `shuffle`, `map`, `reduce`, etc. I actually liked this approach, because noun alone doesn't help you figure out what's happening. When you write `Vehicle.wheels(bicycle, 2)`, what is wheels doing? Is it updating the number of wheels in the bicycle struct? Is it returning the number of wheels of the bicycle as a base-2 integer? Is it fetching the 2 structs representing the first 2 wheels of the bicycle? Wouldn't it be much clearer if it was called `count_wheels`/`set_wheels`/`get_wheels`?
