### ISSUE TITLE
EditorConfig

### ISSUE THREAD

**Issue by eksperimental** [christopheradams/elixir_style_guide#70]
I have not used it myself yet, but I know [many (big) projects](https://github.com/editorconfig/editorconfig/wiki/Projects-Using-EditorConfig) are using it, and it seems a great idea.
http://editorconfig.org/

a `.editorconfig` file that can set stuff like

```
# Unix-style newlines with a newline ending every file
[*]
end_of_line = lf
insert_final_newline = true

#4 space indentation
[*.ex, *.exs, .travis.yml, *.md]
indent_style = space
indent_size = 2
```

and many more such as `charset`, `trim_trailing_whitespace`, `insert_final_newline`

and it is supported by default by the github code editor and viewer, so that's a bonus when people want to contribute also for this guide.

I'm wondering if anybody out there is using it for any elixir project.

So my proposal are:
- Should we include it in the list of tools?
- Should we include use it in this project?
- Should we recommend its usage?

**Comment by eksperimental** [comment]
as a reference, Awesome Elixir is using it
https://github.com/h4cc/awesome-elixir/blob/master/.editorconfig

**Comment by christopheradams** [comment]
An `.editorconfig` seems like an OK idea. Do you want to add it @eksperimental?

**Comment by eksperimental** [comment]
yes. I will, just give me a few days. I have a working copy that i've been using over a year now

**Comment by eksperimental** [comment]
I'm going to work on it, but the questions still remain.

* Should we include it in the list of tools?
* Should we include use it in this project?
* Should we recommend its usage?

**Comment by christopheradams** [comment]
You could mention it in `CONTRIBUTING.md`, as a recommended tool to use if you want to contribute to the style guide and your editor supports it.

**Comment by christopheradams** [comment]
@eksperimental Can you share your `.editorconfig` file?

**Comment by eksperimental** [comment]
sorry, I will submit a PR with everything today

**Comment by eksperimental** [comment]
https://git.io/elixir-editorconfig

**Comment by eksperimental** [comment]
@christopheradams I see there was a misunderstanding. My proposal is to use this https://git.io/elixir-editorconfig file for Elixir projects.
But I think you thought of including one this project itself.
I'm in favor of both, but my main proposal was so people can use it in their own projects

**Comment by christopheradams** [comment]
@eksperimental I think we can do both, by providing a sample `.editorconfig` in the project, which also works for the project (since it has markdown and an .exs file).

**Comment by corroded** [comment]
@christopheradams @eksperimental what's the status of this card? Just checking. Is a sample `.editorconfig` all we need?

**Comment by eksperimental** [comment]
Sorry i am unable to help now. Grab my file and do whatever necessary changes

**Comment by christopheradams** [comment]
With the new formatter, I feel that EditorConfig is outside the scope of what the guide needs to recommend. Closing for now unless someone else wants to take this up. Thanks. :)
