### ISSUE TITLE
When should partials be used?

### ISSUE THREAD

**Issue by frojasg** [christopheradams/elixir_style_guide#74]
Hi 

I was reading the elixir documentations and I would like to know when should we use partials[1]. 

for example, what would be the prefer way to say this 

``` elixir
list = [1, 2, 3]
Enum.find_index(list, &(&1 == 2))
```

or

``` elixir
list = [1, 2, 3]
Enum.find_index(list, fn(x) -> x == 2 end) 
```

[1] http://elixir-lang.org/crash-course.html#partials-in-elixir

**Comment by whatyouhide** [comment]
@frojasg whatever makes the most sense is fine. If you're just passing a named function, `&` is often preferred:

```elixir
Enum.map(["foo", "bar", "baz"], &String.length/1)
#=> [3, 3, 3]
```

In other cases, just choose the one that reads nicer. In the case you're showing above, I personally prefer `&(&1 == 2)` as it's more concise but still clear. Also, note that you *have* to use `fn` in order to take advantage of pattern matching as `&n` doesn't support it:

```elixir
[{:ok, 1}, {:ok, 2}, {:ok, 3}]
|> Enum.map(fn {:ok, x} -> x end)
#=> [1, 2, 3]
```

**Comment by frojasg** [comment]
Thanks @whatyouhide. it makes sense. Do you think is worth document this in the style guide? I could create a PR

**Comment by eksperimental** [comment]
I think @whatyouhide example is a really good one on when to use partials, but still don't know where it would fit in in the style-guide, as having a section for partials just for that it would be too much.
so maybe adding more use cases will make a section worth

**Comment by corroded** [comment]
@eksperimental I think if @frojasg  is still keen on doing the PR, it's good. The [we](https://github.com/christopheradams/elixir_style_guide#testing) [have](https://github.com/christopheradams/elixir_style_guide#metaprogramming) [a bunch](https://github.com/christopheradams/elixir_style_guide#strings) of sections that only have a single rule in them ( [even a section with no rule!](https://github.com/christopheradams/elixir_style_guide#regular-expressions) that I think it can warrant it's own section.

If @frojasg is not keen, I can try making a PR with the examples they made. Thoughts?

**Comment by eksperimental** [comment]
@corroded Agreed. we could have a section named "Functions", which we could later expand on
