### ISSUE TITLE
Using singular or plural when naming a nested directory

### ISSUE THREAD

**Issue by miskolc** [christopheradams/elixir_style_guide#75]
I'm just working on a project where I have several modules that implement supervisors, several modules that implement registries for other modules and several modules that implement queues.
Basically I can name the directories `queues`, `registries` and `supervisors` or `queue`, `registry` and `supervisor`(the choice is between plural and singular).

I've went to check other elixir projects to see what convention they used( like [Phoenix](https://github.com/phoenixframework/phoenix) and [Elixir](https://github.com/elixir-lang/elixir)) and I've noticed that most directory names are singular. But after reading the names of the modules in these directories I feel that in those cases it makes sense to use the singular form because the modules inside that directory are components of the `thing` that the directory name refers to( for example in the [Elixir Kernel](https://github.com/elixir-lang/elixir/tree/master/lib/elixir/lib/kernel) it makes perfect sense to use singular for the `kernel` directory because all the modules inside are components of it).

In my specific case I would have in the directory for queues modules named `requests_queue.ex` and `responses_queue.ex`, both different are two different `types of queues`, and not `components of a queue` functionality, therefore I think it would make sense to use the plural form `queues` for naming the directory( in this specific case). The downside might be that some people might consider it confusing to have both singular and plural used to name directories.

What do you think?

**Comment by eksperimental** [comment]
I'm not sure if I understand your question correctly,
but I think the question is not whether your directories should be named in singular or plural, but your modules, and your directories should be named after your modules.
