### ISSUE TITLE
Linter preset?

### ISSUE THREAD

**Issue by user453584** [christopheradams/elixir_style_guide#82]
Is there a good linter for implementing the details in this style guide (ideally one with a preset of some kind for the styles defined here)?

**Comment by niftyn8** [comment]
I haven't looked at it in a while but last time I checked https://github.com/lpil/dogma wasn't exactly in line with the style guide... but looking through https://github.com/lpil/dogma/blob/master/docs/rules.md real quick it looks like it provides pretty solid defaults if they work for you and looks like it's pretty configurable.

**Comment by eksperimental** [comment]
There's also credo: https://github.com/rrrene/credo
which has it's own style guide: https://github.com/rrrene/elixir-style-guide#credos-elixir-style-guide-

**Comment by eksperimental** [comment]
can we close this one @niftyn8 ?
