### ISSUE TITLE
Blank line between use/import/alias/require groups

### ISSUE THREAD

**Issue by net** [christopheradams/elixir_style_guide#96]
I think it is both more readable and prettier to separate use/import/alias/require groups with a blank line.

``` elixir
# preferred
defmodule MyModule do
  use Xenserver

  import Something
  import SomethingElse

  alias My.Long.Module.Name
  alias My.Other.Module.Name

  require Integer

  ...
end

# not preferred
defmodule MyModule do
  use Xenserver
  import Something
  import SomethingElse
  alias My.Long.Module.Name
  alias My.Other.Module.Name
  require Integer

  ...
end
```

**Comment by tobyhinloopen** [comment]
I don't agree. Better group them in logical groups of related stuff. In this case, it is already documented to group related calls with a new-line

```
defmodule MyModule do
  use XServer
  alias XServer.Foo.Baz

  use HTTPFoo
  import HTTPFooBaz, only: [set_cookie: 999]
end
```

**Comment by christopheradams** [comment]
@net's suggestion is recommended by [another style guide](https://github.com/lexmag/elixir-style-guide/blob/master/README.md#module-layout). That's a point in it's favor.

Grouping based on directive is easy to follow. Grouping based on how "related" they are (same module or close to it? same library?) is not so deterministic.
